plugins {
    id 'com.android.application'
}

android {
    namespace 'com.preg.assist'
    compileSdk 34

    defaultConfig {
        applicationId "com.preg.assist"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
